config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes do
    resources :ingredients
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include Abyme::Model

  has_many :ingredients
  abymize :ingredients, permit: :all_attributes
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def new
    @ingredient = Ingredient.new
  end

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ingredient.update
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to recipes_path
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params

    # Remove cost for recipe ?
    params.require(:ingredient).permit(:name,
                                       :amount_for_recipe,
                                       :cost_for_recipe,
                                       :amount_of_order,
                                       :cost_of_order,
                                       :unit_for_recipe,
                                       :unit_of_order)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def new
    @recipe = Recipe.new
  end

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(abyme_attributes, :name)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abyme/_ingredient_fields.html.erb
<div id="abyme">
  <%= f.hidden_field :_destroy %>
  <%= f.input :name %>
  <%= f.input :amount_for_recipe %>
  <%= f.input :unit_for_recipe %>
  <%= f.input :amount_of_order %>
  <%= f.input :unit_of_order %>
  <%= f.input :cost_of_order %>


  <%= remove_associated_record(content: "-", html: { id: "delete-member" }) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cost price, l'application qui aide à estimer le coût de revient de vos recettes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Cost price vous aide à estimer le coût de revient de vos recettes !</h1>
    <p>Imaginez vos recettes, ajoutez vos ingrédients et l'application se charge du reste</p>
    <%= link_to "J'essaie maintenant", new_recipe_path, class:"main-button" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container p-3">
</div>

app/views/recipes/index.html.erb
<div class="container p-3">
  <h1>Mes recettes</h1>
  <% @recipes.each do |recipe| %>
    <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>

    <h3><%= recipe.cost %></h3>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container p-3">
  <h1>Nouvelle recette</h1>
  <div class="flex">
    <%= simple_form_for(@recipe) do |f| %>
      <%= f.input :name, label: "Nom de la recette" %>

      <%= f.abyme_for(:ingredients) do |abyme| %>
        <%= abyme.records %>
        <%= abyme.new_records %>
        <%= add_associated_record(content: "Ajoute un ingrédient +", html: {class: "main-button"}) %>
      <% end %>

      <%= f.button :submit, class:"main-button" %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<h3>Ma recette</h3>
<p><%= @recipe.name %></p>
<p><%= @recipe.cost %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-resto">
  <%= link_to "Cost price", root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Nouvelle recette", new_recipe_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mes recettes", recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://img.icons8.com/ios/50/000000/user-male-circle.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>